### ISSUE TITLE
--consul-prefix option and path does not exist in Consul

### ISSUE THREAD

**Issue by ryanwilliamson** [rightscale/cmdb#3]
When using the --consul-prefix option if the path you specify does not exist in the Consul key/value store you receive an exception:

cmdb-2.6.1/lib/cmdb/consul_source.rb:62:in `rescue in each_pair': undefined local variable or method`exc' for #CMDB::ConsulSource:0x00000002f17b40 (NameError)

**Comment by xeger** [comment]
Thanks. Closed by #4
